version: '3'
services:

  php:
    build:
      context: .
      dockerfile: dockerfile-php
    image: ${PROJECT_NAME}-php
    tty: true

  nginx:
    build:
      context: .
      dockerfile: dockerfile-nginx
    image: ${PROJECT_NAME}-nginx
    tty: true
